version: '2.4'

services:
  jenkins:
    build: jenkins_controller2
    container_name: jenkins
    ports:
      - "50000:50000"
      - "8880:8080"
    volumes:
      - ./jenkins_controller2/jenkins.yaml:/usr/share/jenkins/ref/jenkins.yaml
    restart: always
  sonarqube:
    depends_on:
      - jenkins
    image: sonarqube:10.2.1-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    restart: always